# Generated by Django 4.0.2 on 2022-03-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
